[project]
name = "2026q2-innovation-sprint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geoai-py>=0.37.1",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "ipympl>=0.10.0",
    "ipywidgets>=8.1.8",
    "termcolor>=3.3.0",
]
